name: python 3.11.5
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - numpy
  - SeqIO
  - Phylo
  - AlignIO
  - Align
  - NCBIWWW
  - NCBIXML
  - ClustalOmegaCommandline
  - DistanceCalculator
  - DistanceTreeConstructor
  - pandas
  - time